// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hahatfiznrlsftmtlolm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhaGF0Zml6bnJsc2Z0bXRsb2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjMyOTcsImV4cCI6MjA2Nzc5OTI5N30.i16hfeNgNKOk7FBi0QGaV4NDotaaOEgo2o0RP8Qrc5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});